name: Haskell CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.6.5'
        cabal-version: '2.4'
    - name: Install dependencies
      run: |
        cabal new-update
        cabal install --only-dependencies --enable-tests
    - name: Build
      run: |
        cabal new-configure --enable-tests
        cabal new-build
    - name: Run tests
      run: cabal new-test
